# -*- coding: utf-8 -*-
"""SpeechWave.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KiIRDOSskEDj3757Axab0k9SLnujGYsS
"""

import gradio as gr
import speech_recognition as sr
import os
from pydub import AudioSegment

recognizer = sr.Recognizer()

def speech_to_text(audio_file):
    try:
        if not audio_file or not os.path.exists(audio_file):
            return "⚠ Error: No valid audio file provided."

        audio = AudioSegment.from_file(audio_file)
        if len(audio) == 0:
            return "⚠ Error: The uploaded audio file is empty."

        wav_file = "converted_audio.wav"
        audio.export(wav_file, format="wav")

        with sr.AudioFile(wav_file) as source:
            audio_data = recognizer.record(source)
            text = recognizer.recognize_google(audio_data)

        return text

    except Exception as e:
        return f"⚠ Error: {str(e)}"

interface = gr.Interface(
    fn=speech_to_text,
    inputs=gr.Audio(type="filepath", label="🎤 Upload Your Audio"),
    outputs=gr.Textbox(label="📝 Converted Speech to Text"),
    title="🌟 SpeechWave: The Smart Audio Transcriber",
    description="Upload your audio (MP3, WAV, etc.), and let SpeechWave convert it to text with impressive accuracy! 🎉",
)

interface.launch(share=True)