# -*- coding: utf-8 -*-
"""SpeechWave.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KiIRDOSskEDj3757Axab0k9SLnujGYsS
"""

!pip install gradio speechrecognition pydub

import gradio as gr
import speech_recognition as sr
from pydub import AudioSegment

recognizer = sr.Recognizer()

def speech_to_text(audio_file):
    try:
        audio = AudioSegment.from_file(audio_file)
        wav_file = "converted_audio.wav"
        audio.export(wav_file, format="wav")

        with sr.AudioFile(wav_file) as source:
            audio_data = recognizer.record(source)
            text = recognizer.recognize_google(audio_data)

        return text

    except Exception as e:
        return f"⚠️ Error: {str(e)}"

custom_css = """
gradio-app {
    background: linear-gradient(135deg, #1f78d1, #4ba1a1, #00bfae, #008f8f); /* Smooth Blue-Green Gradient */
    font-family: 'Arial', sans-serif;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
}

#title {
    color: #ff6f61; /* Coral Red */
    font-size: 30px;
    font-weight: bold;
    text-shadow: 2px 2px 6px rgba(0, 0, 0, 0.3);
    text-align: center;
    margin-bottom: 20px;
}

#desc {
    color: #ffffff;
    font-size: 18px;
    font-style: italic;
    text-shadow: 1px 1px 4px rgba(0, 0, 0, 0.2);
    text-align: center;
    margin-bottom: 30px;
}

gradio-container {
    text-align: center;
}

#input {
    margin-bottom: 20px; /* Add spacing between input and output */
}

#output {
    margin-top: 20px; /* Add spacing between output and input */
}

gradio-button {
    background: radial-gradient(circle, #ff6f61, #ff9e3d) !important; /* Bright Red-Orange Gradient */
    color: white !important;
    font-size: 16px !important;
    border-radius: 15px !important; /* Rounded Buttons */
    box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
    border: 2px solid #ff6f61 !important; /* Coral Border */
}

gradio-textbox {
    border: 2px solid #00bfae;
    border-radius: 8px;
    font-size: 16px;
    padding: 10px;
    color: #333;
}
"""

interface = gr.Interface(
    fn=speech_to_text,
    inputs=gr.Audio(type="filepath", label="🎤 Upload Your Audio"),
    outputs=gr.Textbox(label="📝 Converted Speech to Text"),
    title="🌟 SpeechWave: The Smart Audio Transcriber",
    description="Upload your audio (MP3, WAV, etc.), and let SpeechWave convert it to text with impressive accuracy! 🎉",
    theme="huggingface",
    css=custom_css
)


interface.launch(share=True)